# Generated by Django 4.0.6 on 2022-08-05 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0002_alter_appointment_doctor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='location',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='first_name',
            field=models.CharField(default='some ho', max_length=100),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='last_name',
            field=models.CharField(default='some ho', max_length=150),
        ),
    ]
