# Generated by Django 4.0.6 on 2022-08-05 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0009_alter_schedule_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='location',
        ),
    ]
