# Generated by Django 4.0.6 on 2022-08-11 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0012_alter_schedule_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='lunch_end',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='lunch_start',
        ),
        migrations.AddField(
            model_name='schedule',
            name='break_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='break_start',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
